plugins {
    id 'com.android.application'
}

android {
    namespace 'org.genericdaw.android'
    compileSdk 35

    defaultConfig {
        applicationId 'org.genericdaw.android'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '0.1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
